### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by petuhovskiy** [foxylion/docker-steam-css#4]
Apparently, new version of Counter-Strike: Source was released not so long ago, and now image from Docker Hub gives "server is running older version" error on connect. 

I tried to rebuild an image from this repo, and it worked fine. I guess image can be rebuilt and updated in the Docker Hub, so other users won't have any problems.

**Comment by foxylion** [comment]
Thank you for the info. I just rebuilt it yesterday. Should now work again. :-)
